# Generated by Django 5.1.7 on 2025-03-30 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0002_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
