# Generated by Django 5.1.15 on 2026-01-20 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0003_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='record_first',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_fourth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_second',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_third',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
