# Generated by Django 5.1.12 on 2025-09-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0003_user_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='records',
            field=models.JSONField(default={15: None, 30: None, 60: None, 120: None}, verbose_name='Records'),
        ),
    ]
