# Generated by Django 5.1.15 on 2026-02-10 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0004_user_record_first_user_record_fourth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='record_first',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='record_fourth',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='record_second',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='user',
            name='record_third',
            field=models.IntegerField(default=0),
        ),
    ]
