# Generated by Django 5.1.12 on 2025-09-13 14:53

import YarikType.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0004_user_records'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='records',
            field=models.JSONField(default=YarikType.models.records_default, verbose_name='Records'),
        ),
    ]
