# Generated by Django 5.1.12 on 2025-09-13 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('YarikType', '0005_alter_user_records'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='records',
        ),
        migrations.AddField(
            model_name='user',
            name='record_first',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_fourth',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_second',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='record_third',
            field=models.FloatField(default=0),
        ),
    ]
